routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::middleware(['auth'])->group(function () {
	Route::resource('/contracts', 'ContractController');

	Route::get('/payments/upcoming', 'CmPaymentController@upcoming_payments');
	Route::get('/payments/add/{contract_id}', 'CmPaymentController@add_payment');
	Route::post('/payments/store', 'CmPaymentController@store_payment');
	Route::get('/payments/company', 'CmPaymentController@company_payments');
	Route::resource('/payments', 'CmPaymentController');

	Route::resource('/users', 'UserController');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

use App\Models\CmContract;
use App\Models\CmPayment;
use Auth;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $dates = ['deleted_at'];

    public function contracts()
    {
        return $this->hasMany('App\Models\CmContract', 'created_by');
    }

    public function payments()
    {
        return $this->hasMany('App\Models\CmPayment', 'created_by');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $agency_users = User::withCount(['contracts', 'payments'])
            ->where('broker_agent_id', config('const.BROKER_ID_CVETI'))
            ->get();
        //dd($agency_users);
        
        return view('users.index', [
            'agency_users' => $agency_users,
            ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $username = $user->name;
        $email = $user->email;
        $user->delete();
        
        return redirect("/users")
            ->with('msg_delete', "Агент $username с ел. поща $email беше изтрит успешно!");   
    }
}

resources/views/users/index.blade.php
@extends('layouts.startmin')

@section('content')
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Списък с агенти</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Информация за агенти
                        </div>
                        @include('partials.success_msg')
                        <p>
                              <!-- add Добави плащане btn with form input politsa number/egn_or_eik/customer names -->  
                        </p>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table width="100%" class="table table-striped table-bordered table-hover text-center" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Име</th>
                                        <th>Ел. поща</th>
                                        <th>Роля</th>

                                        <th>Брой договори</th>
                                        <th>Брой плащания</th>                                       
                                        <th>Дата на присъединяване</th>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $num = 1; ?>
                                    @foreach($agency_users as $user)
                                        <tr>
                                            <td>{{$num++}}</td>
                                            <td> {{$user->name}} </td>
                                            <td> {{$user->email}} </td>
                                            <td> {{$user->role}} </td>

                                            <td> {{$user->contracts_count}} </td>
                                            <td> {{$user->payments_count}} </td>
                                            <td> {{Carbon\Carbon::parse($user->created_at)->format('Y-m-d')}}</td>
                                            
                                            <?php $user_id = $user->id; ?>
                                            <td>
                                                <a href='{{url("/users/contracts/$user_id")}}' class="btn btn-info text-center" title="Полици" disabled><i class="fa fa-file-text-o  "></i> Полици </a>
                                            </td>
                                            <td>
                                                <a href='{{url("/users/payments/$user_id")}}' class="btn btn-info text-center" title="Плащания" disabled><i class="fa fa-eur"></i> Плащания </a>
                                            </td>
                                            <td>
                                                <form action='{{url("/users/$user_id")}}' method="POST" onsubmit="return confirm('Наистина ли искате да изтриета този агент?');">
                                                    {{ csrf_field() }}
                                                    {{ method_field('DELETE') }}

                                                    <button type="submit" class="btn btn-danger text-center" title="Изтрий" id="delete">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>

            
@endsection

@section('footer_scripts')
<script src="{{asset('vendor/datatables/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('vendor/datatables-plugins/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('vendor/datatables-responsive/dataTables.responsive.js')}}"></script>

<script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
            "iDisplayLength": 25,
            responsive: true,
        });
    });
</script>


@endsection